"""satlib — shared library for Source Archive Tools.

Single source of truth for behaviour shared across the sat,
collection, archive, and content tier executables. Tier CLIs are thin
wrappers over these functions; permission delegation remains a
filesystem concern (ADR-004) and is not enforced here.
"""

from .archive import (
    ArchiveCollisionError,
    ArchiveExistsError,
    ArchivePlan,
    PROVENANCE_RECORD,
    build_provenance_record,
    create_archive,
    has_provenance,
    plan_archive,
)
from .identity import (
    IDENTIFIER_FIELD,
    IDENTITY_RECORD,
    IdentityError,
    IdentityExistsError,
    MalformedIdentityError,
    backfill_identity,
    build_identity_record,
    has_identity,
    is_valid_identifier,
    new_identifier,
    read_identity,
    write_identity,
)
from .discovery import (
    DiscoveryResult,
    discover,
    is_language_root,
)
from .cascade import (
    CALCULATED,
    TripwireReport,
    cascade,
    resolve_entity,
    verify,
)
from .assets import (
    Orphan,
    assets_dir_for,
    entity_for,
    find_orphans,
    is_assets_name,
    iter_entities,
    read_yaml_asset,
    write_yaml_asset,
)
from .seed import (
    MISFILED_SAMPLE,
    seed_documentation,
    seed_example_collection,
)
from .create import (
    COLLECTIONS_HOME_FIELD,
    COLLECTION_RECORD,
    DEFAULT_COLLECTIONS_HOME,
    create_collection_role,
    create_content_directory,
    create_instance_role,
)
from .migrate import (
    FLAT_RECORDS,
    MIGRATE_COMMAND,
    migrate,
    plan_migration,
)
from .reconcile import (
    CrossArchiveMoveError,
    Evidence,
    Proposal,
    ReconcileError,
    ReconcileFinding,
    apply_reconciliation,
    find_reconcilable,
    gather_evidence,
    move_archive,
    move_collection,
)
from .fixity import (
    CONTAINER_SUFFIXES,
    DEFAULT_ALGORITHM,
    FIXITY_RECORD,
    FixityFinding,
    WRITE_ONCE_RECORDS,
    check_fixity,
    digest_file,
    format_sha256sums,
    read_fixity,
    record_fixity,
)
from .children import (
    CHILDREN_RECORD,
    ChildFinding,
    child_role_for,
    compare_children,
    discover_children,
    read_children,
    rebuild_children_data,
    refresh_children,
    write_children,
)
from .roles import (
    DC_RECORD,
    NAME_FIELD,
    ROLE_ARCHIVE,
    ROLE_COLLECTION,
    ROLE_CONTENT,
    ROLE_SAT,
    ROLES,
    RoleError,
    SPARSE_DC_TEMPLATE_COMMENT,
    declared_roles,
    has_role,
    read_name,
    read_role_yaml,
    role_dir,
    role_path,
    write_name,
    write_role_yaml,
    write_sparse_dc,
)
from .registry import (
    CachedSource,
    CacheResult,
    CacheStatus,
    CacheUnavailableError,
    RegistryCache,
)
from .language import (
    SubtagRegistry,
    TagValidation,
    iana_source,
    non_authority_expression,
    validate_expression,
)
from .spdx import (
    ExceptionList,
    ExpressionValidation,
    LicenseList,
    LicenseValidation,
    spdx_exceptions_source,
    spdx_licenses_source,
    validate_identifier,
    # aliased: satlib.language already owns the top-level
    # ``validate_expression`` name; both peers keep it in-module.
    validate_expression as validate_license_expression,
)
from .work import (
    DOCUMENT_IDENTITY_RECORD,
    DuplicateExpressionError,
    DocumentIdentityExistsError,
    Finding,
    INDEX_SAT_VERSION,
    MalformedDocumentIdentityError,
    UnresolvedAddressError,
    WORK_FIELD,
    WORK_INDEX_RECORD,
    WORK_RETIRED_FIELD,
    WorkError,
    assign_document_identity,
    compare_index,
    has_document_identity,
    join_work,
    read_document_identity,
    read_work_index,
    rebuild_index_data,
    resolve_expression_of,
    update_index_for_document,
    write_work_index,
)

from .cataloging import (
    CatalogResult,
    Finding,
    FrontmatterError,
    apply_cataloging_policy,
    read_frontmatter,
)
from .markdown import (
    DEFAULT_RULES,
    MarkdownError,
    check_house_rules,
    ensure_available as ensure_mdformat_available,
    load_rules as load_markdown_rules,
    normalize as normalize_markdown,
)
from .staging import (
    StagingError,
    promote,
)

__all__ = [
    "CatalogResult",
    "Finding",
    "FrontmatterError",
    "apply_cataloging_policy",
    "read_frontmatter",
    "DEFAULT_RULES",
    "MarkdownError",
    "check_house_rules",
    "ensure_mdformat_available",
    "load_markdown_rules",
    "normalize_markdown",
    "StagingError",
    "promote",
    "ArchiveCollisionError",
    "ArchiveExistsError",
    "ArchivePlan",
    "PROVENANCE_RECORD",
    "build_provenance_record",
    "create_archive",
    "has_provenance",
    "plan_archive",
    "IDENTIFIER_FIELD",
    "IDENTITY_RECORD",
    "IdentityError",
    "IdentityExistsError",
    "MalformedIdentityError",
    "backfill_identity",
    "build_identity_record",
    "has_identity",
    "is_valid_identifier",
    "new_identifier",
    "read_identity",
    "write_identity",
    "DiscoveryResult",
    "discover",
    "is_language_root",
    "CALCULATED",
    "TripwireReport",
    "cascade",
    "resolve_entity",
    "verify",
    "Orphan",
    "assets_dir_for",
    "entity_for",
    "find_orphans",
    "is_assets_name",
    "iter_entities",
    "read_yaml_asset",
    "write_yaml_asset",
    "MISFILED_SAMPLE",
    "seed_documentation",
    "seed_example_collection",
    "COLLECTIONS_HOME_FIELD",
    "COLLECTION_RECORD",
    "DEFAULT_COLLECTIONS_HOME",
    "create_collection_role",
    "create_content_directory",
    "create_instance_role",
    "FLAT_RECORDS",
    "MIGRATE_COMMAND",
    "migrate",
    "plan_migration",
    "CrossArchiveMoveError",
    "Evidence",
    "Proposal",
    "ReconcileError",
    "ReconcileFinding",
    "apply_reconciliation",
    "find_reconcilable",
    "gather_evidence",
    "move_archive",
    "move_collection",
    "CONTAINER_SUFFIXES",
    "DEFAULT_ALGORITHM",
    "FIXITY_RECORD",
    "FixityFinding",
    "WRITE_ONCE_RECORDS",
    "check_fixity",
    "digest_file",
    "format_sha256sums",
    "read_fixity",
    "record_fixity",
    "CHILDREN_RECORD",
    "ChildFinding",
    "child_role_for",
    "compare_children",
    "discover_children",
    "read_children",
    "rebuild_children_data",
    "refresh_children",
    "write_children",
    "DC_RECORD",
    "NAME_FIELD",
    "ROLE_ARCHIVE",
    "ROLE_COLLECTION",
    "ROLE_CONTENT",
    "ROLE_SAT",
    "ROLES",
    "RoleError",
    "SPARSE_DC_TEMPLATE_COMMENT",
    "declared_roles",
    "has_role",
    "read_name",
    "read_role_yaml",
    "role_dir",
    "role_path",
    "write_name",
    "write_role_yaml",
    "write_sparse_dc",
    "CachedSource",
    "CacheResult",
    "CacheStatus",
    "CacheUnavailableError",
    "RegistryCache",
    "SubtagRegistry",
    "TagValidation",
    "iana_source",
    "non_authority_expression",
    "validate_expression",
    "ExceptionList",
    "ExpressionValidation",
    "LicenseList",
    "LicenseValidation",
    "spdx_exceptions_source",
    "spdx_licenses_source",
    "validate_identifier",
    "validate_license_expression",
    "DOCUMENT_IDENTITY_RECORD",
    "DuplicateExpressionError",
    "DocumentIdentityExistsError",
    "Finding",
    "INDEX_SAT_VERSION",
    "MalformedDocumentIdentityError",
    "UnresolvedAddressError",
    "WORK_FIELD",
    "WORK_INDEX_RECORD",
    "WORK_RETIRED_FIELD",
    "WorkError",
    "assign_document_identity",
    "compare_index",
    "has_document_identity",
    "join_work",
    "read_document_identity",
    "read_work_index",
    "rebuild_index_data",
    "resolve_expression_of",
    "update_index_for_document",
    "write_work_index",
]
